Add files-to-ignore-internal-links-in feature
kyma-incubator/milv pull request #6
Opened 2021-02-24 10:24 UTC by dbadura

**Description**

Changes proposed in this pull request:

- implementation `files-to-ignore-internal-links-in`

**Related issue(s)**

2021-02-26 07:04 UTC, tgorgol commented
/test all

2021-02-26 08:04 UTC, tgorgol commented
/test all

2021-02-26 08:05 UTC, tgorgol commented
/test all

2021-02-26 09:26 UTC, tgorgol commented
/test all

2021-03-01 07:45 UTC, tgorgol requested changes
Good job, few comments from me

2021-03-01 07:45 UTC, tgorgol commented on pkg/config_file.go
>  	if config != nil {
```suggestion
	if config == nil {
	  return nil
	}
```

2021-03-01 07:45 UTC, tgorgol commented on pkg/config_file.go
> +	internalIgnore := config.IgnoreExternal
```suggestion
	internalIgnore := config.IgnoreInternal
```

Please cover this case in unit tests

2021-03-01 07:45 UTC, tgorgol commented on pkg/config_file_test.go
> +func TestCombineConfigsForFile(t *testing.T) {
```suggestion
func TestNewFileConfig(t *testing.T) {
```

2021-03-01 10:43 UTC, tgorgol approved these changes
LGTM

2021-03-01 10:46 UTC, kazydek approved these changes

2021-03-01 10:47 UTC, merged